package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * AmArticlemaster generated by hbm2java
 */
public class AmArticlemaster implements java.io.Serializable {

	private String articleNo;
	private String categoryCode;
	private String brandCode;
	private String brandOwner;
	private String carbonationIndicator;
	private String flavorCode;
	private String phyStateCode;
	private String tradeMark;
	private String calorieIndicator;
	private String packageCode;
	private String packageSize;
	private String packageTypeCode;
	private String returnablePackaging;
	private String rtdIndicator;
	private String beverageType;
	private String beverageProduct;
	private String nameShortC;
	private String nameE;
	private String nameC;
	private BigDecimal weightPerCase;
	private String weightUnit;
	private BigDecimal netWeight;
	private BigDecimal volumePerCase;
	private String basisMaterialNumber;
	private String materialGroup;
	private String measureBaseUnit;
	private String genItemCatGrp;
	private String division;
	private String industrySector;
	private String materialType;
	private String salesOrganization;
	private String distributionChannel;
	private String storageBin;
	private Integer totalShelfLife;
	private String dmeMarketMarterial;
	private String barCode;
	private String availabilityCheck;
	private String distrProfile;
	private String loadingGrp;
	private String transGrp;
	private BigDecimal baseQty;
	private String deliveringPlant;
	private String cashDiscountIndicator;
	private BigDecimal minOrderQty;
	private BigDecimal minDelyQty;
	private String measureUnit;
	private BigDecimal deliveryUnit;
	private String departureCountry;
	private String countryName;
	private String taxCategory1;
	private String taxClassification;
	private String accAssignmentGrp;
	private String itemCategoryGroup;
	private String matlSatisticsGrp;
	private String plMarterial;
	private Integer plQty;
	private String promotionalIndicator;
	private String deleteFlag;
	private String swireBrand;
	private String swirePackagegroup;
	private String swireBrandGroup;
	private String positiveMaterialCode;
	private String materialDesc;
	private String supplierMaterialCode;
	private String consumptionType;
	private String sparePartPurpose;
	private String sparePartType;
	private String sparePartSource;
	private String groupCode;
	private String basisModelCode;
	private String basisModelCodeDesc;
	private String materialSubCode;
	private String plantMaterialSubCode;
	private String supplierDesc;
	private BigDecimal doorCount;
	private BigDecimal breakEvenPoint;
	private BigDecimal maintPeriod;
	private String articleSize;
	private Date createDate;
	private String createBy;
	private Date updateDate;
	private String updateBy;

	public AmArticlemaster() {
	}

	public AmArticlemaster(String articleNo, String swireBrand, String swirePackagegroup, String swireBrandGroup,
			Date createDate, String createBy, Date updateDate, String updateBy) {
		this.articleNo = articleNo;
		this.swireBrand = swireBrand;
		this.swirePackagegroup = swirePackagegroup;
		this.swireBrandGroup = swireBrandGroup;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public AmArticlemaster(String articleNo, String categoryCode, String brandCode, String brandOwner,
			String carbonationIndicator, String flavorCode, String phyStateCode, String tradeMark,
			String calorieIndicator, String packageCode, String packageSize, String packageTypeCode,
			String returnablePackaging, String rtdIndicator, String beverageType, String beverageProduct,
			String nameShortC, String nameE, String nameC, BigDecimal weightPerCase, String weightUnit,
			BigDecimal netWeight, BigDecimal volumePerCase, String basisMaterialNumber, String materialGroup,
			String measureBaseUnit, String genItemCatGrp, String division, String industrySector, String materialType,
			String salesOrganization, String distributionChannel, String storageBin, Integer totalShelfLife,
			String dmeMarketMarterial, String barCode, String availabilityCheck, String distrProfile, String loadingGrp,
			String transGrp, BigDecimal baseQty, String deliveringPlant, String cashDiscountIndicator,
			BigDecimal minOrderQty, BigDecimal minDelyQty, String measureUnit, BigDecimal deliveryUnit,
			String departureCountry, String countryName, String taxCategory1, String taxClassification,
			String accAssignmentGrp, String itemCategoryGroup, String matlSatisticsGrp, String plMarterial,
			Integer plQty, String promotionalIndicator, String deleteFlag, String swireBrand, String swirePackagegroup,
			String swireBrandGroup, String positiveMaterialCode, String materialDesc, String supplierMaterialCode,
			String consumptionType, String sparePartPurpose, String sparePartType, String sparePartSource,
			String groupCode, String basisModelCode, String basisModelCodeDesc, String materialSubCode,
			String plantMaterialSubCode, String supplierDesc, BigDecimal doorCount, BigDecimal breakEvenPoint,
			BigDecimal maintPeriod, String articleSize, Date createDate, String createBy, Date updateDate,
			String updateBy) {
		this.articleNo = articleNo;
		this.categoryCode = categoryCode;
		this.brandCode = brandCode;
		this.brandOwner = brandOwner;
		this.carbonationIndicator = carbonationIndicator;
		this.flavorCode = flavorCode;
		this.phyStateCode = phyStateCode;
		this.tradeMark = tradeMark;
		this.calorieIndicator = calorieIndicator;
		this.packageCode = packageCode;
		this.packageSize = packageSize;
		this.packageTypeCode = packageTypeCode;
		this.returnablePackaging = returnablePackaging;
		this.rtdIndicator = rtdIndicator;
		this.beverageType = beverageType;
		this.beverageProduct = beverageProduct;
		this.nameShortC = nameShortC;
		this.nameE = nameE;
		this.nameC = nameC;
		this.weightPerCase = weightPerCase;
		this.weightUnit = weightUnit;
		this.netWeight = netWeight;
		this.volumePerCase = volumePerCase;
		this.basisMaterialNumber = basisMaterialNumber;
		this.materialGroup = materialGroup;
		this.measureBaseUnit = measureBaseUnit;
		this.genItemCatGrp = genItemCatGrp;
		this.division = division;
		this.industrySector = industrySector;
		this.materialType = materialType;
		this.salesOrganization = salesOrganization;
		this.distributionChannel = distributionChannel;
		this.storageBin = storageBin;
		this.totalShelfLife = totalShelfLife;
		this.dmeMarketMarterial = dmeMarketMarterial;
		this.barCode = barCode;
		this.availabilityCheck = availabilityCheck;
		this.distrProfile = distrProfile;
		this.loadingGrp = loadingGrp;
		this.transGrp = transGrp;
		this.baseQty = baseQty;
		this.deliveringPlant = deliveringPlant;
		this.cashDiscountIndicator = cashDiscountIndicator;
		this.minOrderQty = minOrderQty;
		this.minDelyQty = minDelyQty;
		this.measureUnit = measureUnit;
		this.deliveryUnit = deliveryUnit;
		this.departureCountry = departureCountry;
		this.countryName = countryName;
		this.taxCategory1 = taxCategory1;
		this.taxClassification = taxClassification;
		this.accAssignmentGrp = accAssignmentGrp;
		this.itemCategoryGroup = itemCategoryGroup;
		this.matlSatisticsGrp = matlSatisticsGrp;
		this.plMarterial = plMarterial;
		this.plQty = plQty;
		this.promotionalIndicator = promotionalIndicator;
		this.deleteFlag = deleteFlag;
		this.swireBrand = swireBrand;
		this.swirePackagegroup = swirePackagegroup;
		this.swireBrandGroup = swireBrandGroup;
		this.positiveMaterialCode = positiveMaterialCode;
		this.materialDesc = materialDesc;
		this.supplierMaterialCode = supplierMaterialCode;
		this.consumptionType = consumptionType;
		this.sparePartPurpose = sparePartPurpose;
		this.sparePartType = sparePartType;
		this.sparePartSource = sparePartSource;
		this.groupCode = groupCode;
		this.basisModelCode = basisModelCode;
		this.basisModelCodeDesc = basisModelCodeDesc;
		this.materialSubCode = materialSubCode;
		this.plantMaterialSubCode = plantMaterialSubCode;
		this.supplierDesc = supplierDesc;
		this.doorCount = doorCount;
		this.breakEvenPoint = breakEvenPoint;
		this.maintPeriod = maintPeriod;
		this.articleSize = articleSize;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public String getArticleNo() {
		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {
		this.articleNo = articleNo;
	}

	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getBrandCode() {
		return this.brandCode;
	}

	public void setBrandCode(String brandCode) {
		this.brandCode = brandCode;
	}

	public String getBrandOwner() {
		return this.brandOwner;
	}

	public void setBrandOwner(String brandOwner) {
		this.brandOwner = brandOwner;
	}

	public String getCarbonationIndicator() {
		return this.carbonationIndicator;
	}

	public void setCarbonationIndicator(String carbonationIndicator) {
		this.carbonationIndicator = carbonationIndicator;
	}

	public String getFlavorCode() {
		return this.flavorCode;
	}

	public void setFlavorCode(String flavorCode) {
		this.flavorCode = flavorCode;
	}

	public String getPhyStateCode() {
		return this.phyStateCode;
	}

	public void setPhyStateCode(String phyStateCode) {
		this.phyStateCode = phyStateCode;
	}

	public String getTradeMark() {
		return this.tradeMark;
	}

	public void setTradeMark(String tradeMark) {
		this.tradeMark = tradeMark;
	}

	public String getCalorieIndicator() {
		return this.calorieIndicator;
	}

	public void setCalorieIndicator(String calorieIndicator) {
		this.calorieIndicator = calorieIndicator;
	}

	public String getPackageCode() {
		return this.packageCode;
	}

	public void setPackageCode(String packageCode) {
		this.packageCode = packageCode;
	}

	public String getPackageSize() {
		return this.packageSize;
	}

	public void setPackageSize(String packageSize) {
		this.packageSize = packageSize;
	}

	public String getPackageTypeCode() {
		return this.packageTypeCode;
	}

	public void setPackageTypeCode(String packageTypeCode) {
		this.packageTypeCode = packageTypeCode;
	}

	public String getReturnablePackaging() {
		return this.returnablePackaging;
	}

	public void setReturnablePackaging(String returnablePackaging) {
		this.returnablePackaging = returnablePackaging;
	}

	public String getRtdIndicator() {
		return this.rtdIndicator;
	}

	public void setRtdIndicator(String rtdIndicator) {
		this.rtdIndicator = rtdIndicator;
	}

	public String getBeverageType() {
		return this.beverageType;
	}

	public void setBeverageType(String beverageType) {
		this.beverageType = beverageType;
	}

	public String getBeverageProduct() {
		return this.beverageProduct;
	}

	public void setBeverageProduct(String beverageProduct) {
		this.beverageProduct = beverageProduct;
	}

	public String getNameShortC() {
		return this.nameShortC;
	}

	public void setNameShortC(String nameShortC) {
		this.nameShortC = nameShortC;
	}

	public String getNameE() {
		return this.nameE;
	}

	public void setNameE(String nameE) {
		this.nameE = nameE;
	}

	public String getNameC() {
		return this.nameC;
	}

	public void setNameC(String nameC) {
		this.nameC = nameC;
	}

	public BigDecimal getWeightPerCase() {
		return this.weightPerCase;
	}

	public void setWeightPerCase(BigDecimal weightPerCase) {
		this.weightPerCase = weightPerCase;
	}

	public String getWeightUnit() {
		return this.weightUnit;
	}

	public void setWeightUnit(String weightUnit) {
		this.weightUnit = weightUnit;
	}

	public BigDecimal getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(BigDecimal netWeight) {
		this.netWeight = netWeight;
	}

	public BigDecimal getVolumePerCase() {
		return this.volumePerCase;
	}

	public void setVolumePerCase(BigDecimal volumePerCase) {
		this.volumePerCase = volumePerCase;
	}

	public String getBasisMaterialNumber() {
		return this.basisMaterialNumber;
	}

	public void setBasisMaterialNumber(String basisMaterialNumber) {
		this.basisMaterialNumber = basisMaterialNumber;
	}

	public String getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}

	public String getMeasureBaseUnit() {
		return this.measureBaseUnit;
	}

	public void setMeasureBaseUnit(String measureBaseUnit) {
		this.measureBaseUnit = measureBaseUnit;
	}

	public String getGenItemCatGrp() {
		return this.genItemCatGrp;
	}

	public void setGenItemCatGrp(String genItemCatGrp) {
		this.genItemCatGrp = genItemCatGrp;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getIndustrySector() {
		return this.industrySector;
	}

	public void setIndustrySector(String industrySector) {
		this.industrySector = industrySector;
	}

	public String getMaterialType() {
		return this.materialType;
	}

	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	public String getSalesOrganization() {
		return this.salesOrganization;
	}

	public void setSalesOrganization(String salesOrganization) {
		this.salesOrganization = salesOrganization;
	}

	public String getDistributionChannel() {
		return this.distributionChannel;
	}

	public void setDistributionChannel(String distributionChannel) {
		this.distributionChannel = distributionChannel;
	}

	public String getStorageBin() {
		return this.storageBin;
	}

	public void setStorageBin(String storageBin) {
		this.storageBin = storageBin;
	}

	public Integer getTotalShelfLife() {
		return this.totalShelfLife;
	}

	public void setTotalShelfLife(Integer totalShelfLife) {
		this.totalShelfLife = totalShelfLife;
	}

	public String getDmeMarketMarterial() {
		return this.dmeMarketMarterial;
	}

	public void setDmeMarketMarterial(String dmeMarketMarterial) {
		this.dmeMarketMarterial = dmeMarketMarterial;
	}

	public String getBarCode() {
		return this.barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	public String getAvailabilityCheck() {
		return this.availabilityCheck;
	}

	public void setAvailabilityCheck(String availabilityCheck) {
		this.availabilityCheck = availabilityCheck;
	}

	public String getDistrProfile() {
		return this.distrProfile;
	}

	public void setDistrProfile(String distrProfile) {
		this.distrProfile = distrProfile;
	}

	public String getLoadingGrp() {
		return this.loadingGrp;
	}

	public void setLoadingGrp(String loadingGrp) {
		this.loadingGrp = loadingGrp;
	}

	public String getTransGrp() {
		return this.transGrp;
	}

	public void setTransGrp(String transGrp) {
		this.transGrp = transGrp;
	}

	public BigDecimal getBaseQty() {
		return this.baseQty;
	}

	public void setBaseQty(BigDecimal baseQty) {
		this.baseQty = baseQty;
	}

	public String getDeliveringPlant() {
		return this.deliveringPlant;
	}

	public void setDeliveringPlant(String deliveringPlant) {
		this.deliveringPlant = deliveringPlant;
	}

	public String getCashDiscountIndicator() {
		return this.cashDiscountIndicator;
	}

	public void setCashDiscountIndicator(String cashDiscountIndicator) {
		this.cashDiscountIndicator = cashDiscountIndicator;
	}

	public BigDecimal getMinOrderQty() {
		return this.minOrderQty;
	}

	public void setMinOrderQty(BigDecimal minOrderQty) {
		this.minOrderQty = minOrderQty;
	}

	public BigDecimal getMinDelyQty() {
		return this.minDelyQty;
	}

	public void setMinDelyQty(BigDecimal minDelyQty) {
		this.minDelyQty = minDelyQty;
	}

	public String getMeasureUnit() {
		return this.measureUnit;
	}

	public void setMeasureUnit(String measureUnit) {
		this.measureUnit = measureUnit;
	}

	public BigDecimal getDeliveryUnit() {
		return this.deliveryUnit;
	}

	public void setDeliveryUnit(BigDecimal deliveryUnit) {
		this.deliveryUnit = deliveryUnit;
	}

	public String getDepartureCountry() {
		return this.departureCountry;
	}

	public void setDepartureCountry(String departureCountry) {
		this.departureCountry = departureCountry;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getTaxCategory1() {
		return this.taxCategory1;
	}

	public void setTaxCategory1(String taxCategory1) {
		this.taxCategory1 = taxCategory1;
	}

	public String getTaxClassification() {
		return this.taxClassification;
	}

	public void setTaxClassification(String taxClassification) {
		this.taxClassification = taxClassification;
	}

	public String getAccAssignmentGrp() {
		return this.accAssignmentGrp;
	}

	public void setAccAssignmentGrp(String accAssignmentGrp) {
		this.accAssignmentGrp = accAssignmentGrp;
	}

	public String getItemCategoryGroup() {
		return this.itemCategoryGroup;
	}

	public void setItemCategoryGroup(String itemCategoryGroup) {
		this.itemCategoryGroup = itemCategoryGroup;
	}

	public String getMatlSatisticsGrp() {
		return this.matlSatisticsGrp;
	}

	public void setMatlSatisticsGrp(String matlSatisticsGrp) {
		this.matlSatisticsGrp = matlSatisticsGrp;
	}

	public String getPlMarterial() {
		return this.plMarterial;
	}

	public void setPlMarterial(String plMarterial) {
		this.plMarterial = plMarterial;
	}

	public Integer getPlQty() {
		return this.plQty;
	}

	public void setPlQty(Integer plQty) {
		this.plQty = plQty;
	}

	public String getPromotionalIndicator() {
		return this.promotionalIndicator;
	}

	public void setPromotionalIndicator(String promotionalIndicator) {
		this.promotionalIndicator = promotionalIndicator;
	}

	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getSwireBrand() {
		return this.swireBrand;
	}

	public void setSwireBrand(String swireBrand) {
		this.swireBrand = swireBrand;
	}

	public String getSwirePackagegroup() {
		return this.swirePackagegroup;
	}

	public void setSwirePackagegroup(String swirePackagegroup) {
		this.swirePackagegroup = swirePackagegroup;
	}

	public String getSwireBrandGroup() {
		return this.swireBrandGroup;
	}

	public void setSwireBrandGroup(String swireBrandGroup) {
		this.swireBrandGroup = swireBrandGroup;
	}

	public String getPositiveMaterialCode() {
		return this.positiveMaterialCode;
	}

	public void setPositiveMaterialCode(String positiveMaterialCode) {
		this.positiveMaterialCode = positiveMaterialCode;
	}

	public String getMaterialDesc() {
		return this.materialDesc;
	}

	public void setMaterialDesc(String materialDesc) {
		this.materialDesc = materialDesc;
	}

	public String getSupplierMaterialCode() {
		return this.supplierMaterialCode;
	}

	public void setSupplierMaterialCode(String supplierMaterialCode) {
		this.supplierMaterialCode = supplierMaterialCode;
	}

	public String getConsumptionType() {
		return this.consumptionType;
	}

	public void setConsumptionType(String consumptionType) {
		this.consumptionType = consumptionType;
	}

	public String getSparePartPurpose() {
		return this.sparePartPurpose;
	}

	public void setSparePartPurpose(String sparePartPurpose) {
		this.sparePartPurpose = sparePartPurpose;
	}

	public String getSparePartType() {
		return this.sparePartType;
	}

	public void setSparePartType(String sparePartType) {
		this.sparePartType = sparePartType;
	}

	public String getSparePartSource() {
		return this.sparePartSource;
	}

	public void setSparePartSource(String sparePartSource) {
		this.sparePartSource = sparePartSource;
	}

	public String getGroupCode() {
		return this.groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getBasisModelCode() {
		return this.basisModelCode;
	}

	public void setBasisModelCode(String basisModelCode) {
		this.basisModelCode = basisModelCode;
	}

	public String getBasisModelCodeDesc() {
		return this.basisModelCodeDesc;
	}

	public void setBasisModelCodeDesc(String basisModelCodeDesc) {
		this.basisModelCodeDesc = basisModelCodeDesc;
	}

	public String getMaterialSubCode() {
		return this.materialSubCode;
	}

	public void setMaterialSubCode(String materialSubCode) {
		this.materialSubCode = materialSubCode;
	}

	public String getPlantMaterialSubCode() {
		return this.plantMaterialSubCode;
	}

	public void setPlantMaterialSubCode(String plantMaterialSubCode) {
		this.plantMaterialSubCode = plantMaterialSubCode;
	}

	public String getSupplierDesc() {
		return this.supplierDesc;
	}

	public void setSupplierDesc(String supplierDesc) {
		this.supplierDesc = supplierDesc;
	}

	public BigDecimal getDoorCount() {
		return this.doorCount;
	}

	public void setDoorCount(BigDecimal doorCount) {
		this.doorCount = doorCount;
	}

	public BigDecimal getBreakEvenPoint() {
		return this.breakEvenPoint;
	}

	public void setBreakEvenPoint(BigDecimal breakEvenPoint) {
		this.breakEvenPoint = breakEvenPoint;
	}

	public BigDecimal getMaintPeriod() {
		return this.maintPeriod;
	}

	public void setMaintPeriod(BigDecimal maintPeriod) {
		this.maintPeriod = maintPeriod;
	}

	public String getArticleSize() {
		return this.articleSize;
	}

	public void setArticleSize(String articleSize) {
		this.articleSize = articleSize;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
