package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * CmCustomercontact generated by hbm2java
 */
public class CmCustomercontact implements java.io.Serializable {

	private String outletNo;
	private String companyCode;
	private String phone1;
	private String phone2;
	private String fax;
	private String email;
	private String contact;
	private String supervisor;
	private String supervisorCard;
	private Date customerBirthday;
	private Date createDate;
	private String createBy;
	private Date updateDate;
	private String updateBy;

	public CmCustomercontact() {
	}

	public CmCustomercontact(String outletNo, String companyCode, Date createDate, String createBy, Date updateDate,
			String updateBy) {
		this.outletNo = outletNo;
		this.companyCode = companyCode;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public CmCustomercontact(String outletNo, String companyCode, String phone1, String phone2, String fax,
			String email, String contact, String supervisor, String supervisorCard, Date customerBirthday,
			Date createDate, String createBy, Date updateDate, String updateBy) {
		this.outletNo = outletNo;
		this.companyCode = companyCode;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.fax = fax;
		this.email = email;
		this.contact = contact;
		this.supervisor = supervisor;
		this.supervisorCard = supervisorCard;
		this.customerBirthday = customerBirthday;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public String getOutletNo() {
		return this.outletNo;
	}

	public void setOutletNo(String outletNo) {
		this.outletNo = outletNo;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	public String getSupervisorCard() {
		return this.supervisorCard;
	}

	public void setSupervisorCard(String supervisorCard) {
		this.supervisorCard = supervisorCard;
	}

	public Date getCustomerBirthday() {
		return this.customerBirthday;
	}

	public void setCustomerBirthday(Date customerBirthday) {
		this.customerBirthday = customerBirthday;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
