package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

/**
 * CsOrderitemId generated by hbm2java
 */
public class CsOrderitemId implements java.io.Serializable {

	private String tranCode;
	private int itemNo;

	public CsOrderitemId() {
	}

	public CsOrderitemId(String tranCode, int itemNo) {
		this.tranCode = tranCode;
		this.itemNo = itemNo;
	}

	public String getTranCode() {
		return this.tranCode;
	}

	public void setTranCode(String tranCode) {
		this.tranCode = tranCode;
	}

	public int getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(int itemNo) {
		this.itemNo = itemNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CsOrderitemId))
			return false;
		CsOrderitemId castOther = (CsOrderitemId) other;

		return ((this.getTranCode() == castOther.getTranCode()) || (this.getTranCode() != null
				&& castOther.getTranCode() != null && this.getTranCode().equals(castOther.getTranCode())))
				&& (this.getItemNo() == castOther.getItemNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTranCode() == null ? 0 : this.getTranCode().hashCode());
		result = 37 * result + this.getItemNo();
		return result;
	}

}
