package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

/**
 * CsOrderitem generated by hbm2java
 */
public class CsOrderitem implements java.io.Serializable {

	private CsOrderitemId id;
	private String companyCode;
	private String articleNo;
	private Integer cases;
	private Integer pieces;
	private String usageCode;
	private BigDecimal productTotal;
	private BigDecimal depositTotal;
	private BigDecimal oninvoiceDiscountTotal;
	private BigDecimal offinvoiceDiscountTotal;
	private Character freeGoodsFlg;
	private String unit;

	public CsOrderitem() {
	}

	public CsOrderitem(CsOrderitemId id, String companyCode) {
		this.id = id;
		this.companyCode = companyCode;
	}

	public CsOrderitem(CsOrderitemId id, String companyCode, String articleNo, Integer cases, Integer pieces,
			String usageCode, BigDecimal productTotal, BigDecimal depositTotal, BigDecimal oninvoiceDiscountTotal,
			BigDecimal offinvoiceDiscountTotal, Character freeGoodsFlg, String unit) {
		this.id = id;
		this.companyCode = companyCode;
		this.articleNo = articleNo;
		this.cases = cases;
		this.pieces = pieces;
		this.usageCode = usageCode;
		this.productTotal = productTotal;
		this.depositTotal = depositTotal;
		this.oninvoiceDiscountTotal = oninvoiceDiscountTotal;
		this.offinvoiceDiscountTotal = offinvoiceDiscountTotal;
		this.freeGoodsFlg = freeGoodsFlg;
		this.unit = unit;
	}

	public CsOrderitemId getId() {
		return this.id;
	}

	public void setId(CsOrderitemId id) {
		this.id = id;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getArticleNo() {
		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {
		this.articleNo = articleNo;
	}

	public Integer getCases() {
		return this.cases;
	}

	public void setCases(Integer cases) {
		this.cases = cases;
	}

	public Integer getPieces() {
		return this.pieces;
	}

	public void setPieces(Integer pieces) {
		this.pieces = pieces;
	}

	public String getUsageCode() {
		return this.usageCode;
	}

	public void setUsageCode(String usageCode) {
		this.usageCode = usageCode;
	}

	public BigDecimal getProductTotal() {
		return this.productTotal;
	}

	public void setProductTotal(BigDecimal productTotal) {
		this.productTotal = productTotal;
	}

	public BigDecimal getDepositTotal() {
		return this.depositTotal;
	}

	public void setDepositTotal(BigDecimal depositTotal) {
		this.depositTotal = depositTotal;
	}

	public BigDecimal getOninvoiceDiscountTotal() {
		return this.oninvoiceDiscountTotal;
	}

	public void setOninvoiceDiscountTotal(BigDecimal oninvoiceDiscountTotal) {
		this.oninvoiceDiscountTotal = oninvoiceDiscountTotal;
	}

	public BigDecimal getOffinvoiceDiscountTotal() {
		return this.offinvoiceDiscountTotal;
	}

	public void setOffinvoiceDiscountTotal(BigDecimal offinvoiceDiscountTotal) {
		this.offinvoiceDiscountTotal = offinvoiceDiscountTotal;
	}

	public Character getFreeGoodsFlg() {
		return this.freeGoodsFlg;
	}

	public void setFreeGoodsFlg(Character freeGoodsFlg) {
		this.freeGoodsFlg = freeGoodsFlg;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

}
