package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * CsOrderheader generated by hbm2java
 */
public class CsOrderheader implements java.io.Serializable {

	private String tranCode;
	private String companyCode;
	private String sbiTranCode;
	private String docCode;
	private String orderType;
	private String usageCode;
	private String shipmentCode;
	private String outletNoSoldto;
	private String outletNoShipto;
	private String deliveryType;
	private String deliveryTypeDesc;
	private String paymentTerms;
	private String delLocationCode;
	private String storageLocation;
	private Date deliveryDate;
	private Date callingDate;
	private float productTotal;
	private float emptyTotal;
	private Date pricingDate;
	private String staffCode;
	private String salesRouteCode;
	private Integer directshipResult;
	private Integer autoreleaseType;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private Date syncDate;

	public CsOrderheader() {
	}

	public CsOrderheader(String tranCode, String companyCode, String sbiTranCode, String docCode, String shipmentCode,
			String outletNoSoldto, String outletNoShipto, String paymentTerms, String delLocationCode,
			Date deliveryDate, float productTotal, float emptyTotal, Date createDate, Date updateDate, Date syncDate) {
		this.tranCode = tranCode;
		this.companyCode = companyCode;
		this.sbiTranCode = sbiTranCode;
		this.docCode = docCode;
		this.shipmentCode = shipmentCode;
		this.outletNoSoldto = outletNoSoldto;
		this.outletNoShipto = outletNoShipto;
		this.paymentTerms = paymentTerms;
		this.delLocationCode = delLocationCode;
		this.deliveryDate = deliveryDate;
		this.productTotal = productTotal;
		this.emptyTotal = emptyTotal;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.syncDate = syncDate;
	}

	public CsOrderheader(String tranCode, String companyCode, String sbiTranCode, String docCode, String orderType,
			String usageCode, String shipmentCode, String outletNoSoldto, String outletNoShipto, String deliveryType,
			String deliveryTypeDesc, String paymentTerms, String delLocationCode, String storageLocation,
			Date deliveryDate, Date callingDate, float productTotal, float emptyTotal, Date pricingDate,
			String staffCode, String salesRouteCode, Integer directshipResult, Integer autoreleaseType, String createBy,
			Date createDate, String updateBy, Date updateDate, Date syncDate) {
		this.tranCode = tranCode;
		this.companyCode = companyCode;
		this.sbiTranCode = sbiTranCode;
		this.docCode = docCode;
		this.orderType = orderType;
		this.usageCode = usageCode;
		this.shipmentCode = shipmentCode;
		this.outletNoSoldto = outletNoSoldto;
		this.outletNoShipto = outletNoShipto;
		this.deliveryType = deliveryType;
		this.deliveryTypeDesc = deliveryTypeDesc;
		this.paymentTerms = paymentTerms;
		this.delLocationCode = delLocationCode;
		this.storageLocation = storageLocation;
		this.deliveryDate = deliveryDate;
		this.callingDate = callingDate;
		this.productTotal = productTotal;
		this.emptyTotal = emptyTotal;
		this.pricingDate = pricingDate;
		this.staffCode = staffCode;
		this.salesRouteCode = salesRouteCode;
		this.directshipResult = directshipResult;
		this.autoreleaseType = autoreleaseType;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.syncDate = syncDate;
	}

	public String getTranCode() {
		return this.tranCode;
	}

	public void setTranCode(String tranCode) {
		this.tranCode = tranCode;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getSbiTranCode() {
		return this.sbiTranCode;
	}

	public void setSbiTranCode(String sbiTranCode) {
		this.sbiTranCode = sbiTranCode;
	}

	public String getDocCode() {
		return this.docCode;
	}

	public void setDocCode(String docCode) {
		this.docCode = docCode;
	}

	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	public String getUsageCode() {
		return this.usageCode;
	}

	public void setUsageCode(String usageCode) {
		this.usageCode = usageCode;
	}

	public String getShipmentCode() {
		return this.shipmentCode;
	}

	public void setShipmentCode(String shipmentCode) {
		this.shipmentCode = shipmentCode;
	}

	public String getOutletNoSoldto() {
		return this.outletNoSoldto;
	}

	public void setOutletNoSoldto(String outletNoSoldto) {
		this.outletNoSoldto = outletNoSoldto;
	}

	public String getOutletNoShipto() {
		return this.outletNoShipto;
	}

	public void setOutletNoShipto(String outletNoShipto) {
		this.outletNoShipto = outletNoShipto;
	}

	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	public String getDeliveryTypeDesc() {
		return this.deliveryTypeDesc;
	}

	public void setDeliveryTypeDesc(String deliveryTypeDesc) {
		this.deliveryTypeDesc = deliveryTypeDesc;
	}

	public String getPaymentTerms() {
		return this.paymentTerms;
	}

	public void setPaymentTerms(String paymentTerms) {
		this.paymentTerms = paymentTerms;
	}

	public String getDelLocationCode() {
		return this.delLocationCode;
	}

	public void setDelLocationCode(String delLocationCode) {
		this.delLocationCode = delLocationCode;
	}

	public String getStorageLocation() {
		return this.storageLocation;
	}

	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}

	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public Date getCallingDate() {
		return this.callingDate;
	}

	public void setCallingDate(Date callingDate) {
		this.callingDate = callingDate;
	}

	public float getProductTotal() {
		return this.productTotal;
	}

	public void setProductTotal(float productTotal) {
		this.productTotal = productTotal;
	}

	public float getEmptyTotal() {
		return this.emptyTotal;
	}

	public void setEmptyTotal(float emptyTotal) {
		this.emptyTotal = emptyTotal;
	}

	public Date getPricingDate() {
		return this.pricingDate;
	}

	public void setPricingDate(Date pricingDate) {
		this.pricingDate = pricingDate;
	}

	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	public String getSalesRouteCode() {
		return this.salesRouteCode;
	}

	public void setSalesRouteCode(String salesRouteCode) {
		this.salesRouteCode = salesRouteCode;
	}

	public Integer getDirectshipResult() {
		return this.directshipResult;
	}

	public void setDirectshipResult(Integer directshipResult) {
		this.directshipResult = directshipResult;
	}

	public Integer getAutoreleaseType() {
		return this.autoreleaseType;
	}

	public void setAutoreleaseType(Integer autoreleaseType) {
		this.autoreleaseType = autoreleaseType;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getSyncDate() {
		return this.syncDate;
	}

	public void setSyncDate(Date syncDate) {
		this.syncDate = syncDate;
	}

}
