package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * CsRouteheader generated by hbm2java
 */
public class CsRouteheader implements java.io.Serializable {

	private String shipmentCode;
	private String companyCode;
	private String shipmentType;
	private String shipmentTypeDesc;
	private String shipmentStatus;
	private String transportPlanPoint;
	private String delLocationCode;
	private Date delDate;
	private byte delStatus;
	private Date delStatusDate;
	private String phoneNo;
	private String driverNo;
	private String driverName;
	private String setllementLocCode;
	private byte printFlag;
	private String printBy;
	private Date printDate;
	private byte confirmStatus;
	private Date confirmDate;
	private String confirmBy;
	private String sapReturnStatus;
	private String sapReturnMessage;
	private Integer sapCheckinStatus;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private Character fsvStatus;
	private Date fsvDate;
	private Long checkinRequestNo;

	public CsRouteheader() {
	}

	public CsRouteheader(String shipmentCode, String companyCode, String shipmentType, String shipmentTypeDesc,
			String shipmentStatus, String delLocationCode, Date delDate, byte delStatus, String phoneNo,
			String driverNo, String driverName, String setllementLocCode, byte printFlag, byte confirmStatus,
			Date createDate, Date updateDate) {
		this.shipmentCode = shipmentCode;
		this.companyCode = companyCode;
		this.shipmentType = shipmentType;
		this.shipmentTypeDesc = shipmentTypeDesc;
		this.shipmentStatus = shipmentStatus;
		this.delLocationCode = delLocationCode;
		this.delDate = delDate;
		this.delStatus = delStatus;
		this.phoneNo = phoneNo;
		this.driverNo = driverNo;
		this.driverName = driverName;
		this.setllementLocCode = setllementLocCode;
		this.printFlag = printFlag;
		this.confirmStatus = confirmStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public CsRouteheader(String shipmentCode, String companyCode, String shipmentType, String shipmentTypeDesc,
			String shipmentStatus, String transportPlanPoint, String delLocationCode, Date delDate, byte delStatus,
			Date delStatusDate, String phoneNo, String driverNo, String driverName, String setllementLocCode,
			byte printFlag, String printBy, Date printDate, byte confirmStatus, Date confirmDate, String confirmBy,
			String sapReturnStatus, String sapReturnMessage, Integer sapCheckinStatus, String createBy, Date createDate,
			String updateBy, Date updateDate, Character fsvStatus, Date fsvDate, Long checkinRequestNo) {
		this.shipmentCode = shipmentCode;
		this.companyCode = companyCode;
		this.shipmentType = shipmentType;
		this.shipmentTypeDesc = shipmentTypeDesc;
		this.shipmentStatus = shipmentStatus;
		this.transportPlanPoint = transportPlanPoint;
		this.delLocationCode = delLocationCode;
		this.delDate = delDate;
		this.delStatus = delStatus;
		this.delStatusDate = delStatusDate;
		this.phoneNo = phoneNo;
		this.driverNo = driverNo;
		this.driverName = driverName;
		this.setllementLocCode = setllementLocCode;
		this.printFlag = printFlag;
		this.printBy = printBy;
		this.printDate = printDate;
		this.confirmStatus = confirmStatus;
		this.confirmDate = confirmDate;
		this.confirmBy = confirmBy;
		this.sapReturnStatus = sapReturnStatus;
		this.sapReturnMessage = sapReturnMessage;
		this.sapCheckinStatus = sapCheckinStatus;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.fsvStatus = fsvStatus;
		this.fsvDate = fsvDate;
		this.checkinRequestNo = checkinRequestNo;
	}

	public String getShipmentCode() {
		return this.shipmentCode;
	}

	public void setShipmentCode(String shipmentCode) {
		this.shipmentCode = shipmentCode;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getShipmentType() {
		return this.shipmentType;
	}

	public void setShipmentType(String shipmentType) {
		this.shipmentType = shipmentType;
	}

	public String getShipmentTypeDesc() {
		return this.shipmentTypeDesc;
	}

	public void setShipmentTypeDesc(String shipmentTypeDesc) {
		this.shipmentTypeDesc = shipmentTypeDesc;
	}

	public String getShipmentStatus() {
		return this.shipmentStatus;
	}

	public void setShipmentStatus(String shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

	public String getTransportPlanPoint() {
		return this.transportPlanPoint;
	}

	public void setTransportPlanPoint(String transportPlanPoint) {
		this.transportPlanPoint = transportPlanPoint;
	}

	public String getDelLocationCode() {
		return this.delLocationCode;
	}

	public void setDelLocationCode(String delLocationCode) {
		this.delLocationCode = delLocationCode;
	}

	public Date getDelDate() {
		return this.delDate;
	}

	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	public byte getDelStatus() {
		return this.delStatus;
	}

	public void setDelStatus(byte delStatus) {
		this.delStatus = delStatus;
	}

	public Date getDelStatusDate() {
		return this.delStatusDate;
	}

	public void setDelStatusDate(Date delStatusDate) {
		this.delStatusDate = delStatusDate;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getDriverNo() {
		return this.driverNo;
	}

	public void setDriverNo(String driverNo) {
		this.driverNo = driverNo;
	}

	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getSetllementLocCode() {
		return this.setllementLocCode;
	}

	public void setSetllementLocCode(String setllementLocCode) {
		this.setllementLocCode = setllementLocCode;
	}

	public byte getPrintFlag() {
		return this.printFlag;
	}

	public void setPrintFlag(byte printFlag) {
		this.printFlag = printFlag;
	}

	public String getPrintBy() {
		return this.printBy;
	}

	public void setPrintBy(String printBy) {
		this.printBy = printBy;
	}

	public Date getPrintDate() {
		return this.printDate;
	}

	public void setPrintDate(Date printDate) {
		this.printDate = printDate;
	}

	public byte getConfirmStatus() {
		return this.confirmStatus;
	}

	public void setConfirmStatus(byte confirmStatus) {
		this.confirmStatus = confirmStatus;
	}

	public Date getConfirmDate() {
		return this.confirmDate;
	}

	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	public String getConfirmBy() {
		return this.confirmBy;
	}

	public void setConfirmBy(String confirmBy) {
		this.confirmBy = confirmBy;
	}

	public String getSapReturnStatus() {
		return this.sapReturnStatus;
	}

	public void setSapReturnStatus(String sapReturnStatus) {
		this.sapReturnStatus = sapReturnStatus;
	}

	public String getSapReturnMessage() {
		return this.sapReturnMessage;
	}

	public void setSapReturnMessage(String sapReturnMessage) {
		this.sapReturnMessage = sapReturnMessage;
	}

	public Integer getSapCheckinStatus() {
		return this.sapCheckinStatus;
	}

	public void setSapCheckinStatus(Integer sapCheckinStatus) {
		this.sapCheckinStatus = sapCheckinStatus;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Character getFsvStatus() {
		return this.fsvStatus;
	}

	public void setFsvStatus(Character fsvStatus) {
		this.fsvStatus = fsvStatus;
	}

	public Date getFsvDate() {
		return this.fsvDate;
	}

	public void setFsvDate(Date fsvDate) {
		this.fsvDate = fsvDate;
	}

	public Long getCheckinRequestNo() {
		return this.checkinRequestNo;
	}

	public void setCheckinRequestNo(Long checkinRequestNo) {
		this.checkinRequestNo = checkinRequestNo;
	}

}
