package hbclass;
// Generated Jan 11, 2017 1:51:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * SbocEmployee generated by hbm2java
 */
public class SbocEmployee implements java.io.Serializable {

	private String empCode;
	private String companyCode;
	private String empType;
	private String empName;
	private String routeId;
	private String routeIdRts;
	private String locationCode;
	private String phone;
	private String email;
	private String suppress;
	private Date suppressDate;
	private Date createDate;
	private String createBy;
	private Date updateDate;
	private String updateBy;
	private String domainAccount;

	public SbocEmployee() {
	}

	public SbocEmployee(String empCode, String companyCode, String empType, Date createDate, String createBy,
			Date updateDate, String updateBy) {
		this.empCode = empCode;
		this.companyCode = companyCode;
		this.empType = empType;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
	}

	public SbocEmployee(String empCode, String companyCode, String empType, String empName, String routeId,
			String routeIdRts, String locationCode, String phone, String email, String suppress, Date suppressDate,
			Date createDate, String createBy, Date updateDate, String updateBy, String domainAccount) {
		this.empCode = empCode;
		this.companyCode = companyCode;
		this.empType = empType;
		this.empName = empName;
		this.routeId = routeId;
		this.routeIdRts = routeIdRts;
		this.locationCode = locationCode;
		this.phone = phone;
		this.email = email;
		this.suppress = suppress;
		this.suppressDate = suppressDate;
		this.createDate = createDate;
		this.createBy = createBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.domainAccount = domainAccount;
	}

	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getEmpType() {
		return this.empType;
	}

	public void setEmpType(String empType) {
		this.empType = empType;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getRouteId() {
		return this.routeId;
	}

	public void setRouteId(String routeId) {
		this.routeId = routeId;
	}

	public String getRouteIdRts() {
		return this.routeIdRts;
	}

	public void setRouteIdRts(String routeIdRts) {
		this.routeIdRts = routeIdRts;
	}

	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSuppress() {
		return this.suppress;
	}

	public void setSuppress(String suppress) {
		this.suppress = suppress;
	}

	public Date getSuppressDate() {
		return this.suppressDate;
	}

	public void setSuppressDate(Date suppressDate) {
		this.suppressDate = suppressDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getDomainAccount() {
		return this.domainAccount;
	}

	public void setDomainAccount(String domainAccount) {
		this.domainAccount = domainAccount;
	}

}
